FROM node:14

WORKDIR /WORKERHOME

COPY ./worker/package.json ./worker/package.json
COPY ./apilibrary/package.json ./apilibrary/package.json

RUN cd ./apilibrary && npm install
RUN cd ./worker && npm install
RUN npm install typescript -g

COPY ./apilibrary ./apilibrary
COPY ./worker ./worker


RUN cd apilibrary && tsc
RUN cd worker && tsc



CMD ["node", "./worker/build/index.js"]